# Импорты всех моделей
from .brands import *
from .cdn_accounts import *
from .settings import *
from .templates import *
from .keywords import *
from .domain_checks import *
from .users import *
from .registrars import *
from .sites import *
from .domain_status import *
from .domain_redirect_history import *
from .domains import *
